-- Created in production on 2026-05-20
DROP TABLE IF EXISTS cranes CASCADE;

CREATE TABLE IF NOT EXISTS cranes (
  id SERIAL PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP WITH TIME ZONE NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  name TEXT,
  terminal_id INTEGER NOT NULL,
  birth_id INTEGER NOT NULL,
  status_id INTEGER NOT NULL
);
